#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

modprobe -q ide-generic

[ -e /proc/ide ] || return

for drive in /proc/ide/*; do
	[ -e ${drive}/media ] || continue
	# nothing to do if the device has already been took in charge
	unit=${drive#/proc/ide/}
	[ -d /sys/block/$unit ] && continue

	read media < $drive/media
	case "$media" in
		disk)   MODULE=ide-disk ;;
		cdrom)  MODULE=ide-cd ;;
		tape)   MODULE=ide-tape ;;
		floppy) MODULE=ide-floppy ;;
		*)      MODULE=ide-generic ;;
	esac

	modprobe -q ${MODULE}
done
