#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

case "$DPKG_ARCH" in
powerpc|ppc64)
	while read line; do
		if [ "${line}" =! "${line#machine*PS3PF}" ]; then 
			# For PS3's we know these devices will exist,
			# and that we'll need them
			modprobe ps3_storage
			modprobe gelic_net
			modprobe ohci-hcd
			modprobe ehci-hcd
		fi
	done < /proc/cpuinfo
	;;
esac
