#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# For ACPI systems
modprobe -Qb fan
modprobe -Qb thermal

# For ppc64 systems
modprobe -Qb therm_pm72
