#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# For ACPI systems
modprobe -q fan
modprobe -q thermal

# For ppc64 systems
modprobe -q therm_pm72
