#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

case "$DPKG_ARCH" in
# load the right modules
powerpc|ppc64)
	modprobe -q therm_pm72
	;;
i386|amd64|ia64)
	modprobe -q fan
	modprobe -q thermal
	;;
esac
