#!/bin/sh -x

mkdir /sys
mkdir /proc
mkdir /tmp
mount -t sysfs sysfs /sys
mount -t proc proc /proc

. /conf/initramfs.conf
. /scripts/functions

# Parse command line options
export init=/sbin/init
export root=
export readonly=y
export break=
export rootmnt=/root
for x in $(cat /proc/cmdline); do
	case $x in
	init=*)
		INIT=${x#init=}
		;;
	root=*)
		ROOT=${x#root=}
		;;
	nfsroot=*)
		NFSROOT=${x#nfsroot=}
		;;
	boot=*)
		BOOT=${x#boot=}
		;;
	ro)
		readonly=y
		;;
	rw)
		readonly=n
		;;
	break)
		break=yes
		;;
	esac
done

run_scripts /scripts/init-top

. /scripts/${BOOT}

load_modules

# Populate /dev tree
udevstart

if [ x${break} = xyes ]; then 
	panic "Spawning shell within the initramfs"
fi

mountroot

run_scripts /scripts/init-bottom

umount /sys
umount /proc

# Chain to real filesystem
exec run-init ${rootmnt} ${init} "$@"
