#!/bin/sh

set -eu

usage()
{
	echo "Usage: $(basename $0) <initramfs file>"
}

if [ "$#" -eq 0 ] ; then
	usage >&2
	exit 1
fi

if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
	usage
	exit 0
fi

for i in "$*" ; do
	if ! [ -r "$i" ] ; then
		echo "Specified file could not be read." >&2
		exit 1
	else
		echo "$i"
		zcat "$i" | cpio --extract --verbose --quiet --list
		fi
done
