.TH UPDATE-INITRAMFS 8  "$Date: 2006/02/17" $" "" "update-initramfs manual"

.SH NAME
update-initramfs \- generate an initramfs image

.SH SYNOPSIS
.B update-initramfs
.RB [ \-k 
.IR version ] 
.RB [ \-c ] 
.RB [ \-u ] 
.RB [ \-t ] 
.RB [ \-v ] 
.RB [ \-h ] 
.SH DESCRIPTION
The
.B update-initramfs 
script manages your initramfs images on your local box.
It keeps track of the existing initramfs archives in /boot.
There are three modes of operation create, update or delete.
You must at least specify one of those modes.

The initramfs is a gzipped cpio archive. 
At boot time, the kernel unpacks that archive into RAM disk, mounts and 
uses it as initial root file system. All finding of the root device 
happens in this early userspace.

.SH OPTIONS
.TP
\fB \-k \fI version
Set the kernel version for whom the initramfs will be generated.
For example the output of uname -r for your currently running kernel.

.TP
\fB \-c
This mode creates a new initramfs.

.TP
\fB \-u
This mode updates an existing initramfs.

.TP
\fB \-d
This mode removes an existing initramfs.

.TP
\fB \-t
Allows to take over an custom initramfs with a newer one.

.TP
\fB \-v
This option increases the amount of information you are given during
the chosen action.

.TP
\fB \-h
Print a short help page describing the available options in 
.B update-initramfs.

.SH AUTHOR
The initramfs-tools are written by Jeff Bailey <jbailey@ubuntu.com>.
This manual is maintained by Maximilian Attems <maks@sternwelten.at>.

.SH SEE ALSO

.BR initramfs.conf (5), initramfs-tools (8), mkinitramfs (8)
