#!/bin/sh

exec >&3

echo "-- /proc/cmdline"
cat /proc/cmdline
echo

echo "-- /proc/filesystems"
grep -v nodev /proc/filesystems
echo

echo "-- lsmod"
lsmod
echo

if [ -r /etc/kernel-img.conf ]; then
	echo "-- kernel-img.conf"
	cat /etc/kernel-img.conf
	echo
fi
