#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ ! -x /sbin/evms_activate ]; then
	exit 0
fi

cp /sbin/evms_activate ${DESTDIR}/sbin

EVMS_VERSION=$(/usr/sbin/evms_query info | grep "EVMS Version" | awk '{ print $3; }')

mkdir -p ${DESTDIR}/lib/evms/${EVMS_VERSION}

for x in disk lvm2 dos multipath; do
	cp /lib/evms/${EVMS_VERSION}/${x}* ${DESTDIR}/lib/evms/${EVMS_VERSION}
done
