#!/bin/sh

OPTION=FRAMEBUFFER
PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_modules_dir kernel/drivers/char/agp
copy_modules_dir kernel/drivers/gpu

manual_add_modules fbcon
manual_add_modules vesafb
manual_add_modules vga16fb

# Programs used for detecting nvidia-legacy-71 hardware during framebuffer init
copy_exec /usr/bin/lspci /bin
copy_exec /usr/bin/cut /bin
copy_exec /bin/grep /bin

for x in ${MODULESDIR}/initrd/*; do
	x=${x##*/}
	x=${x%.*}
	case ${x} in
	'*')
		break
		;;
	*fb)
		fbcon=y
		;;
	esac

	manual_add_modules ${x}
done
