#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading loading extra kernel bits into the initramfs

. /usr/share/initramfs-tools/hook-functions

fbcon=n
set -x

for x in ${MODULESDIR}/initrd/*; do
	x=${x##*/}
	x=${x%.*}
	case ${x} in
	'*')
		break
		;;
	*fb)
		fbcon=y
		;;
	esac

	force_load ${x}
done

if [ ${fbcon} = "y" ]; then
	force_load fbcon
fi

