#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# FIXME: Remove this hook after Lenny releases
if [ -x /sbin/vgchange ] && [ -d /lib/lvm-200 ] \
	&& [ ! -f /usr/share/initramfs-tools/hooks/lvm2 ]; then
	copy_exec /lib/lvm-200/vgchange /sbin
	for x in dm_mod dm_snapshot dm_mirror; do
		manual_add_modules ${x}
	done
fi
exit 0
