#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# FIXME: check /sys/block/dm-0/dev
if [ ! -x /sbin/vgchange ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

cp /lib/lvm-200/vgchange "${DESTDIR}/sbin"

for x in dm_mod; do
        manual_add_modules ${x}
done
