#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/vgchange ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /lib/lvm-200/vgchange /sbin

for x in dm_mod dm_snapshot; do
        manual_add_modules ${x}
done
