#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/mdadm ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/mdadm /sbin
copy_exec /sbin/mdrun /sbin

for x in md linear raid0 raid1 raid5 raid6 raid10; do
        manual_add_modules ${x}
done
