#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading thermal bits into the initramfs

. /usr/share/initramfs-tools/hook-functions

case "$DPKG_ARCH" in
# copy the right modules
powerpc|ppc64)
	if [ -e /sys/bus/ps3_system_bus/ ]; then
		exit 0
	fi
	manual_add_modules therm_pm72
	manual_add_modules windfarm_core
	manual_add_modules windfarm_cpufreq_clamp
	manual_add_modules windfarm_lm75_sensor
	manual_add_modules windfarm_max6690_sensor
	manual_add_modules windfarm_pid
	manual_add_modules windfarm_pm112
	manual_add_modules windfarm_pm81
	manual_add_modules windfarm_pm91
	manual_add_modules windfarm_smu_controls
	manual_add_modules windfarm_smu_sat
	manual_add_modules windfarm_smu_sensors
	manual_add_modules i2c-powermac
	;;
i386|amd64|ia64)
	manual_add_modules fan
	manual_add_modules thermal
	;;
esac
