#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading thermal bits into the initramfs

. /usr/share/initramfs-tools/hook-functions

# ACPI Systems
for x in fan thermal; do
	manual_add_modules ${x}
done

# PPC64 Systems
manual_add_modules therm_pm72
