#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# udev really wants to be able to do socket communications to udevd
# This means that there's a bit of a race condition as the events come
# flooding in and the kernels ability to autoload the 'unix' module.

# We solve the problem thusly.  Hopefully RIP Ubuntu# 12915

. /usr/share/initramfs-tools/hook-functions

force_load unix

cp -a /etc/udev ${DESTDIR}/etc

# Hack until udev is built with klibc
copy_exec /sbin/udevd /sbin
copy_exec /sbin/udevsynthesize /sbin

mkdir "${DESTDIR}/lib/udev"
copy_exec /lib/udev/udevsynthesize /lib/udev
