#!/bin/sh
# FIXME: kill after lenny release
# needed for UUID root and partial etch upgrades
#
PREREQ="udev"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# should never happen
if [ ! -e $DESTDIR/lib/udev/ ]; then
	exit 0
fi

# fixed udev hook
if [ -e $DESTDIR/lib/udev/ ] && [ -e $DESTDIR/lib/udev/hotplug.functions ]; then
	exit 0
fi

cp /lib/udev/hotplug.functions $DESTDIR/lib/udev/
for program in /lib/udev/*_id; do
	copy_exec $program /lib/udev/
done
exit 0
