#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

evms=${ROOT#/dev/evms/}

case ${evms} in
	/dev/root)
		unset evms
		;;
	/*)
		exit 0
		;;
esac
	
for module in dm-mod linear raid0 raid1 raid10 raid5 raid6; do
	modprobe -q $module
done

/sbin/evms_activate
