#!/bin/sh

PREREQ="md"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

vg=$(echo ${ROOT} | sed -e 's#/dev/mapper/\(.*\)-.*#\1#')

[ x${vg} != x ] || return

modprobe -q dm-mod

vgchange -ay ${vg}
