#!/bin/sh

PREREQ="md"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

vg=${ROOT#/dev/mapper/}

case ${vg} in
	/dev/root)
		unset vg
		;;
	/*)
		exit 0
		;;
esac
	
modprobe -Qb dm-mod

vgchange -ay

