#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

unset raidlvl
gotraid=n

# Detect raid level
for x in /dev/hd[a-z][0-9]* /dev/sd[a-z][0-9]*; do
	if [ ! -e ${x} ]; then
		continue
	fi
	raidlvl=$(mdadm --examine ${x} 2>/dev/null | grep "Level" | sed -e 's/.*Raid Level : \(.*\)/\1/')
	if [ "$raidlvl" ]; then
		modprobe -q ${raidlvl} 2>/dev/null
		gotraid=y
	fi
done

[ "${gotraid}" = y ] || exit

/sbin/mdrun /dev
