#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

unset raidlvl

# Detect raid level
for x in /dev/hd* /dev/sd*; do
	raidlvl=$(mdadm --examine ${x} | grep "Level" | sed -e 's/.*Raid Level : \(.*\)/\1/')
	modprobe -q ${raidlvl}
done

[ x${raidlvl} != x ] || return

/sbin/mdrun /dev
