#!/bin/sh

PREREQ="udev_helper"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ -e /scripts/local-top/mdadm ]; then
	exit 0
fi

unset raidlvl
gotraid=n

# Detect raid level
for x in /dev/hd[a-z][0-9]* /dev/sd[a-z][0-9]*; do
	if [ ! -e ${x} ]; then
		continue
	fi
	raidlvl=$(mdadm --examine ${x} 2>/dev/null | grep "Level" | sed -e 's/.*Raid Level : \(.*\)/\1/')
	if [ "$raidlvl" ]; then
		modprobe -q ${raidlvl} 2>/dev/null
		gotraid=y
	fi
done

[ "${gotraid}" = y ] || exit

# source the presumed root md and it's info
. ./conf/mdrun.conf

# assemble root raid first due to initrd-tools compatibility
mdadm -A ${rootraiddev} -R -u $uuid $devices

# assemble all raid devices
/sbin/mdrun /dev
