#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# If we're booting from IDE, it might not be a PCI controller,
# but might be an old fashioned ISA controller; in which case
# we need to load ide-generic.
if [ ! -e "${ROOT}" -o "${ROOT}" = "/dev/root" ]; then
    modprobe -q ide-generic
fi
