#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ "x${resume}" = "x" ]; then
	exit
fi

if [ ! -e "${resume}" ]; then
	exit
fi

if [ -e /sys/power/resume ]; then
	major_minor=$(ls -l ${resume} | awk '{printf "%d:%d", $5, $6}')
	echo $major_minor >/sys/power/resume
fi
