#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [ "x${resume}" = "x" ]; then
	exit
fi

case $resume in
	LABEL=*)
	resume="/dev/disk/by-label/${resume#LABEL=}"
	;;
	UUID=*)
	resume="/dev/disk/by-uuid/${resume#UUID=}"
	;;
esac

if [ ! -e "${resume}" ]; then
	exit
fi

if [ -e /sys/power/resume ]; then
#	FIXME: klibc-utils resume needs more tests
#	resume ${resume}
	major_minor=$(ls -l ${resume} | awk '{printf "%d:%d", $5, $6}')
	echo $major_minor >/sys/power/resume
fi
